version: '3.8'

services:
  piggino-api:
    container_name: piggino-api
    build:
      context: ./backend
      dockerfile: Piggino.Api/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/piggino.db
    restart: unless-stopped

  piggino-frontend:
    container_name: piggino-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8081:8081" # Expõe apenas a porta 8081 para o acesso local
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  data:
  caddy_data:
  caddy_config: