# docker-compose.yml
version: '3.8'

services:
  piggino-api:
    container_name: piggino-api
    build:
      context: ./backend
      dockerfile: Piggino.Api/Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      # Passa a chave do arquivo .env para a variável de ambiente dentro do contêiner
      - JwtSettings__Key=${JWT_KEY}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/piggino.db
    networks:
      - piggino-net

  piggino-frontend:
    container_name: piggino-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - piggino-net

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - piggino-net

volumes:
  data:
  caddy_data:
  caddy_config:

networks:
  piggino-net:
    driver: bridge