version: '3.8'

services:
  # Serviço do Backend (API) - Sem alterações
  piggino-api:
    container_name: piggino-api
    build:
      context: ./backend
      dockerfile: Piggino.Api/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/piggino.db
    restart: unless-stopped

  # Serviço do Frontend - A porta foi removida
  piggino-frontend:
    container_name: piggino-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    # A porta foi removida daqui, pois o Caddy vai gerenciar o acesso

  # NOVO SERVIÇO: Caddy
  caddy:
     image: caddy:latest
     container_name: caddy
     restart: unless-stopped
     ports:
       # Vamos expor APENAS a porta segura 443
       - "443:443"
     volumes:
       - ./caddy/Caddyfile:/etc/caddy/Caddyfile
       - caddy_data:/data
       - caddy_config:/config

volumes:
  data:
  caddy_data:
  caddy_config: