# docker-compose.yml (Versão final para CI/CD)
version: '3.8'

services:
  piggino-api:
    image: bielborgesc/piggino-api:latest
    container_name: piggino-api
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - JwtSettings__Key=${JWT_KEY}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/piggino.db
    command: >
      sh -c "dotnet ef database update && dotnet Piggino.Api.dll"
    networks:
      - piggino-net

  piggino-frontend:
    # A imagem virá do Docker Hub
    image: bielborgesc/piggino-frontend:latest
    container_name: piggino-frontend
    restart: unless-stopped
    networks:
      - piggino-net

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - piggino-net

volumes:
  data:
  caddy_data:
  caddy_config:

networks:
  piggino-net:
    driver: bridge